lib: [
  "/home/d4hines/repos/stupid-consensus/_esy/default/store/b/consensus-408e24c3/install/default/lib/consensus/Consensus.a"
  "/home/d4hines/repos/stupid-consensus/_esy/default/store/b/consensus-408e24c3/install/default/lib/consensus/Consensus.cma"
  "/home/d4hines/repos/stupid-consensus/_esy/default/store/b/consensus-408e24c3/install/default/lib/consensus/Consensus.cmxa"
  "/home/d4hines/repos/stupid-consensus/_esy/default/store/b/consensus-408e24c3/install/default/lib/consensus/META"
  "/home/d4hines/repos/stupid-consensus/_esy/default/store/b/consensus-408e24c3/install/default/lib/consensus/consensus.cmi"
  "/home/d4hines/repos/stupid-consensus/_esy/default/store/b/consensus-408e24c3/install/default/lib/consensus/consensus.cmt"
  "/home/d4hines/repos/stupid-consensus/_esy/default/store/b/consensus-408e24c3/install/default/lib/consensus/consensus.cmx"
  "/home/d4hines/repos/stupid-consensus/_esy/default/store/b/consensus-408e24c3/install/default/lib/consensus/consensus.ml"
  "/home/d4hines/repos/stupid-consensus/_esy/default/store/b/consensus-408e24c3/install/default/lib/consensus/dune-package"
  "/home/d4hines/repos/stupid-consensus/_esy/default/store/b/consensus-408e24c3/install/default/lib/consensus/opam"
]
libexec: [
  "/home/d4hines/repos/stupid-consensus/_esy/default/store/b/consensus-408e24c3/install/default/lib/consensus/Consensus.cmxs"
]
bin: [
  "/home/d4hines/repos/stupid-consensus/_esy/default/store/b/consensus-408e24c3/install/default/bin/main"
]
doc: [
  "/home/d4hines/repos/stupid-consensus/_esy/default/store/b/consensus-408e24c3/install/default/doc/consensus/README.md"
]
